const $ = (id) => document.getElementById(id);

export const DOM = {
  game: $('game'), background: $('background'), titleScreen: $('titleScreen'), newGameBtn: $('newGameBtn'), continueBtn: $('continueBtn'),
  hud: $('hud'), hudLocation: $('hudLocation'), hudTime: $('hudTime'), storyLocationPlaque: $('storyLocationPlaque'), storyLocationText: $('storyLocationText'), storyMenuHex: $('storyMenuHex'),
  character: $('character'), dialogueBox: $('dialogueBox'), speakerRole: $('speakerRole'), speaker: $('speaker'), dialogue: $('dialogue'), choices: $('choices'),
  backpackBtn: $('backpackBtn'), backpackCount: $('backpackCount'), nameModal: $('nameModal'), nameInput: $('nameInput'), nameConfirm: $('nameConfirm'),
  inventoryModal: $('inventoryModal'), inventoryClose: $('inventoryClose'), inventoryList: $('inventoryList'), mapModal: $('mapModal'), mapClose: $('mapClose'), mapGrid: $('mapGrid'), mapTime: $('mapTime'), mapLocation: $('mapLocation'),
  systemModal: $('systemModal'), systemBtn: $('systemBtn'), systemClose: $('systemClose'), volumeSlider: $('volumeSlider'), saveBtn: $('saveBtn'), loadBtn: $('loadBtn'), restartBtn: $('restartBtn'), saveInfo: $('saveInfo'), notice: $('notice'),
  quickMenu: $('quickMenu'), mapBtn: $('mapBtn'), quickSaveBtn: $('quickSaveBtn'), quickLoadBtn: $('quickLoadBtn'), bgm: $('bgm'),
  battleScreen: $('battleScreen'), battleWave: $('battleWave'), battleTurn: $('battleTurn'), phaseLabel: $('phaseLabel'), targetLines: $('targetLines'), turnOrder: $('turnOrder'), battleDon: $('battleDon'), donActionSprite: $('donActionSprite'), battleEnemy: $('battleEnemy'), battleArena: $('battleArena'), enemyRoster: $('enemyRoster'), combatTotal: $('combatTotal'), donUnit: $('donUnit'), enemyUnit: $('enemyUnit'),
  donHpBar: $('donHpBar'), donHpText: $('donHpText'), donSpBar: $('donSpBar'), donSpText: $('donSpText'), donSpeed: $('donSpeed'), donStatus: $('donStatus'),
  enemyHpBar: $('enemyHpBar'), enemyHpText: $('enemyHpText'), enemyStaggerBar: $('enemyStaggerBar'), enemyStaggerText: $('enemyStaggerText'), enemySpeed: $('enemySpeed'), enemyStatus: $('enemyStatus'),
  battleInspector: $('battleInspector'), inspectorName: $('inspectorName'), inspectorArt: $('inspectorArt'), inspectorPower: $('inspectorPower'), inspectorText: $('inspectorText'), inspectorKeywords: $('inspectorKeywords'),
  battleKeywordPanel: $('battleKeywordPanel'), keywordName: $('keywordName'), keywordText: $('keywordText'), battleMatchup: $('battleMatchup'), matchDonArt: $('matchDonArt'), matchDonSpeed: $('matchDonSpeed'), matchDonSkill: $('matchDonSkill'), matchDonCoins: $('matchDonCoins'), matchDonPower: $('matchDonPower'), matchForecast: $('matchForecast'), matchEnemyPower: $('matchEnemyPower'), matchEnemySpeed: $('matchEnemySpeed'), matchEnemySkill: $('matchEnemySkill'), matchEnemyCoins: $('matchEnemyCoins'),
  enemySkillInspector: $('enemySkillInspector'), enemyInspectorArt: $('enemyInspectorArt'), enemyInspectorName: $('enemyInspectorName'), enemyInspectorType: $('enemyInspectorType'), enemyInspectorCoins: $('enemyInspectorCoins'), enemyInspectorPower: $('enemyInspectorPower'), enemyInspectorText: $('enemyInspectorText'),
  battleTutorial: $('battleTutorial'), tutorialTitle: $('tutorialTitle'), tutorialText: $('tutorialText'), battleIntro: $('battleIntro'), battleIntroStep: $('battleIntroStep'), battleIntroTitle: $('battleIntroTitle'), battleIntroText: $('battleIntroText'), battleIntroPrev: $('battleIntroPrev'), battleIntroNext: $('battleIntroNext'), battleIntroSkip: $('battleIntroSkip'),
  enemyIntentSlots: $('enemyIntentSlots'), actionRail: $('actionRail'), planningPanel: $('planningPanel'), commandCluster: document.querySelector('.lc4-command'), autoCluster: document.querySelector('.lc4-auto'), startCombatBtn: $('startCombatBtn'), autoWinBtn: $('autoWinBtn'), autoDamageBtn: $('autoDamageBtn'), managerSp: $('managerSp'), sinLust: $('sinLust'), sinEnvy: $('sinEnvy'), sinGluttony: $('sinGluttony'),
  clashOverlay: $('clashOverlay'), clashDonSkill: $('clashDonSkill'), clashDonArt: $('clashDonArt'), clashEnemySkill: $('clashEnemySkill'), clashEnemyArt: $('clashEnemyArt'), clashDonPower: $('clashDonPower'), clashEnemyPower: $('clashEnemyPower'), clashCoinsDon: $('clashCoinsDon'), clashCoinsEnemy: $('clashCoinsEnemy'), clashResult: $('clashResult'), combatLog: $('combatLog'), donDamage: $('donDamage'), enemyDamage: $('enemyDamage'), battleResult: $('battleResult'), battleResultSmall: $('battleResultSmall'), battleResultTitle: $('battleResultTitle'), battleContinue: $('battleContinue'), battleFxLayer: $('battleFxLayer'), skillCutin: $('skillCutin'), skillCutinArt: $('skillCutinArt'), skillCutinAffinity: $('skillCutinAffinity'), skillCutinName: $('skillCutinName'), coinBurst: $('coinBurst'), screenFlash: $('screenFlash'),
};

export { $ };
